version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - .:/codefiction
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        depends_on:
                  - "php"
    php:
        build: .
        volumes:
            - ./:/codefiction
        networks:
            - code-network
        environment:
                - DEVELOPMENT=true
        command: "bash -c 'sh /codefiction/install.sh'"
        working_dir: '/codefiction'
networks:
    code-network:
        driver: bridge
